"""
memory.py — Episodic memory compression via LLM.

Implements SwarmSim-Architecture.md §6.  Every 7 sim-days the coordinator
triggers a compression call for each agent.  The call produces a ≤75-token
natural-language summary of the agent's notable experiences, replacing their
previous episodic_memory.

Volume: ~1.4% extra inference on top of the tick decision calls.
  (1,000 agents × 1 compression / 7 days = 143 compressions per 7-day period,
   vs. 1,000 agents × 24 ticks/day × 7 days = 168,000 tick calls)

Compression prompt:
    Block A (system, same as decision prompt — benefits from prefix cache)
    Mini Block B (agent profile summary, abbreviated)
    Compression Block (structured bullet list of notable events from the period)
    Task Block (produce the ≤75-token memory summary)

The coordinator calls should_compress() each midnight to check which agents
are due, gathers their event logs, and calls run_compression_batch() to get
updated memory strings via Aurora Swarm scatter_gather.

Usage:
    from swarmsim.memory import (
        should_compress, build_compression_prompt,
        run_compression_batch, parse_compression_response,
    )

    # Each midnight:
    due = [a for a in agents if should_compress(a, sim_day)]
    if due:
        # gather event data built during the week
        results = await run_compression_batch(due, event_logs, pool)
        for agent_id, new_memory in results.items():
            agent_map[agent_id].episodic_memory = new_memory
            agent_map[agent_id].last_compression_day = sim_day
"""

from __future__ import annotations

import re
from typing import Optional

from .models import Agent
from . import sim_config as cfg


# ═══════════════════════════════════════════════════════════════════════════════
# Compression schedule
# ═══════════════════════════════════════════════════════════════════════════════

def should_compress(agent: Agent, sim_day: int) -> bool:
    """
    Return True if this agent is due for episodic memory compression today.

    Compresses every EPISODIC_COMPRESSION_INTERVAL_DAYS days, starting from
    the first interval boundary after the agent's last compression.
    Dead agents are skipped.
    """
    if not agent.is_active:
        return False
    interval = cfg.EPISODIC_COMPRESSION_INTERVAL_DAYS
    return (sim_day - agent.last_compression_day) >= interval


# ═══════════════════════════════════════════════════════════════════════════════
# Prompt construction
# ═══════════════════════════════════════════════════════════════════════════════

_COMPRESSION_SYSTEM = (
    "You are helping to build a memory summary for a simulated Chicago resident "
    "during the COVID-19 pandemic (March–June 2020). "
    "Your task is to compress a list of notable events from the past week into "
    "a concise personal memory — 1–3 sentences, maximum 75 tokens. "
    "Write in first person, past tense. Be specific about what mattered most. "
    "Do not repeat information that is already in the agent's existing memory "
    "unless it has changed significantly. "
    "Output only the memory text — no preamble, no labels, no quotes."
)

_COMPRESSION_PROFILE_TEMPLATE = (
    "{name}, {age}-year-old {occupation} in Logan Square. "
    "{comorbidity_note}"
    "Disease state: {disease_state}."
)

_COMPRESSION_TASK_TEMPLATE = (
    "Existing memory (may be empty on first compression):\n"
    "{existing_memory}\n\n"
    "Notable events from the past {interval} days:\n"
    "{event_bullets}\n\n"
    "Write the updated memory (≤75 tokens, first person, past tense):"
)


def build_compression_prompt(
    agent:       Agent,
    event_log:   list[str],
    sim_day:     int,
) -> str:
    """
    Build the full compression prompt for a single agent.

    event_log: list of notable event strings accumulated since last compression.
               These are generated by the coordinator (disease transitions,
               isolation decisions, social network events, etc.)
    """
    # Abbreviated profile (not full Block B — just key facts)
    comorbidity_note = (
        f"Has: {', '.join(agent.comorbidities[:2])}. "
        if agent.comorbidities else ""
    )
    profile = _COMPRESSION_PROFILE_TEMPLATE.format(
        name=agent.synthetic_name,
        age=agent.age,
        occupation=agent.occupation_type.replace("_", " "),
        comorbidity_note=comorbidity_note,
        disease_state=agent.disease_state,
    )

    # Event bullets
    if event_log:
        bullets = "\n".join(f"- {e}" for e in event_log)
    else:
        bullets = "- No notable events this period."

    existing = agent.episodic_memory.strip() or "(none)"
    interval = cfg.EPISODIC_COMPRESSION_INTERVAL_DAYS

    task = _COMPRESSION_TASK_TEMPLATE.format(
        existing_memory=existing,
        interval=interval,
        event_bullets=bullets,
    )

    return f"{_COMPRESSION_SYSTEM}\n\n{profile}\n\n{task}"


# ═══════════════════════════════════════════════════════════════════════════════
# Response parsing
# ═══════════════════════════════════════════════════════════════════════════════

_MAX_MEMORY_TOKENS = 75    # hard cap; truncate by word if needed
_MAX_MEMORY_WORDS  = 85    # approximate word ceiling (tokens ≈ words × 1.1)


def parse_compression_response(raw: str, agent: Agent) -> str:
    """
    Clean and truncate the LLM's compression output.

    Returns a string of ≤75 tokens (approximated as ≤85 words).
    Falls back to the agent's existing memory if the response is unusable.
    """
    if not raw:
        return agent.episodic_memory

    # Strip markdown fences, leading/trailing whitespace, and label prefixes
    text = raw.strip()
    text = re.sub(r"^```[a-z]*\n?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\n?```$", "", text)
    text = re.sub(r"^(memory:|summary:|updated memory:)\s*", "", text,
                  flags=re.IGNORECASE)
    text = text.strip()

    # Reject empty or suspiciously short outputs
    if len(text) < 10:
        return agent.episodic_memory

    # Truncate to word ceiling
    words = text.split()
    if len(words) > _MAX_MEMORY_WORDS:
        words = words[:_MAX_MEMORY_WORDS]
        text  = " ".join(words) + "…"

    return text


# ═══════════════════════════════════════════════════════════════════════════════
# Batch runner (async — requires an active AgentPool / VLLMPool)
# ═══════════════════════════════════════════════════════════════════════════════

async def run_compression_batch(
    agents:     list[Agent],
    event_logs: dict[int, list[str]],    # agent_id → event list
    pool,                                 # aurora_swarm.AgentPool or VLLMPool
    sim_day:    int,
    model:      str = cfg.MODEL,
    max_tokens: int = 100,
) -> dict[int, str]:
    """
    Run episodic memory compression for a batch of agents via Aurora Swarm.

    Uses scatter_gather to send all compression prompts in parallel and
    collect updated memory strings.

    Returns:
        dict mapping agent_id → new memory string (already parsed/cleaned).
        Agents whose compression fails retain their existing memory.
    """
    from aurora_swarm.patterns.scatter_gather import scatter_gather

    prompts = []
    ordered_agents = []
    for agent in agents:
        log_entries = event_logs.get(agent.agent_id, [])
        prompt = build_compression_prompt(agent, log_entries, sim_day)
        prompts.append(prompt)
        ordered_agents.append(agent)

    if not prompts:
        return {}

    responses = await scatter_gather(pool=pool, prompts=prompts)
    raw_responses = [r.text if r.success else "" for r in responses]

    results: dict[int, str] = {}
    for agent, raw in zip(ordered_agents, raw_responses):
        memory = parse_compression_response(raw, agent)
        results[agent.agent_id] = memory

    return results


# ═══════════════════════════════════════════════════════════════════════════════
# Event log builder helpers (used by coordinator to populate event_logs dict)
# ═══════════════════════════════════════════════════════════════════════════════

def record_disease_event(
    event_log: list[str],
    agent:     Agent,
    new_state: str,
    sim_day:   int,
) -> None:
    """
    Append a disease transition event to this agent's weekly event log.
    Called by coordinator after run_midnight_tick().
    """
    _STATE_DESCRIPTIONS = {
        "EXPOSED":            f"Day {sim_day}: Was exposed to COVID-19.",
        "PRE-SYMPTOMATIC":    f"Day {sim_day}: Entered pre-symptomatic phase of COVID.",
        "ASYMPTOMATIC":       f"Day {sim_day}: Tested positive (asymptomatic).",
        "SYMPTOMATIC-MILD":   f"Day {sim_day}: Developed mild COVID symptoms (fever, cough).",
        "SYMPTOMATIC-SEVERE": f"Day {sim_day}: Became seriously ill with COVID.",
        "HOSPITALIZED":       f"Day {sim_day}: Was hospitalized due to COVID.",
        "ICU":                f"Day {sim_day}: Was admitted to the ICU.",
        "RECOVERED":          f"Day {sim_day}: Recovered from COVID.",
    }
    desc = _STATE_DESCRIPTIONS.get(new_state)
    if desc:
        event_log.append(desc)


def record_isolation_event(
    event_log:     list[str],
    agent:         Agent,
    sim_day:       int,
    reason:        str = "",
) -> None:
    """
    Record a voluntary or policy-driven isolation event.
    reason: short string like "fear", "symptoms", "policy"
    """
    label = f" due to {reason}" if reason else ""
    event_log.append(f"Day {sim_day}: Stayed home{label}.")


def record_contact_event(
    event_log: list[str],
    sim_day:   int,
    event:     str,
) -> None:
    """
    Record a notable social network event (contact hospitalized, deceased, etc.).
    event: human-readable description, e.g. "A neighbor was hospitalized."
    """
    event_log.append(f"Day {sim_day}: {event}")


# ═══════════════════════════════════════════════════════════════════════════════
# CLI smoke test (no LLM — tests prompt construction and parsing only)
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    from .population import generate_population
    from . import sim_config as cfg

    agents, places = generate_population(n_agents=50, seed=cfg.RANDOM_SEED,
                                         use_osmnx=False)
    agent_map = {a.agent_id: a for a in agents}

    # Simulate 7 days of events for a few agents
    sim_day = 7

    # Agent 0: became symptomatic, isolated
    a0 = agents[0]
    a0.disease_state     = "SYMPTOMATIC-MILD"
    a0.symptom_onset_day = 4
    a0.episodic_memory   = ""

    log0: list[str] = []
    record_disease_event(log0, a0, "EXPOSED",          sim_day=2)
    record_disease_event(log0, a0, "SYMPTOMATIC-MILD", sim_day=4)
    record_isolation_event(log0, a0, sim_day=4, reason="symptoms")
    record_isolation_event(log0, a0, sim_day=5, reason="symptoms")
    record_isolation_event(log0, a0, sim_day=6, reason="symptoms")
    record_contact_event(log0, sim_day=5, event="A neighbor was hospitalized with COVID.")

    # Agent 1: healthy, no events
    a1 = agents[1]
    log1: list[str] = []

    # Agent 2: recovered, has existing memory
    a2 = agents[2]
    a2.disease_state   = "RECOVERED"
    a2.episodic_memory = "Caught COVID early in the outbreak and recovered after a difficult week."

    log2: list[str] = []
    record_disease_event(log2, a2, "RECOVERED", sim_day=7)
    record_contact_event(log2, sim_day=6, event="An elderly neighbor died of COVID.")

    print("[memory] Compression prompt construction test\n")
    print("=" * 70)

    for agent, log in [(a0, log0), (a1, log1), (a2, log2)]:
        print(f"\n── Agent {agent.agent_id}: {agent.synthetic_name} "
              f"({agent.occupation_type}, state={agent.disease_state}) ──")
        print(f"   should_compress(day={sim_day}): {should_compress(agent, sim_day)}")
        prompt = build_compression_prompt(agent, log, sim_day)
        print(f"   Prompt ({len(prompt.split())} words):\n")
        # Show just the task block for brevity
        task_start = prompt.find("Existing memory")
        if task_start >= 0:
            print("   [system+profile omitted]")
            print("   " + prompt[task_start:].replace("\n", "\n   "))
        print()

    # Test parse_compression_response
    print("=" * 70)
    print("\n── parse_compression_response tests ──")

    test_cases = [
        ("I've been sick with COVID for three days now. Isolated at home, worried about my elderly neighbors.", True),
        ("```\nSpent the week mostly at home.\n```", True),
        ("Memory: Recovered from COVID after a hard week. Lost someone in my network.", True),
        ("", False),         # empty → keep existing
        ("ok", False),       # too short → keep existing
        ("word " * 90,  True),  # too long → truncated
    ]

    a2.episodic_memory = "Caught COVID early and recovered."
    for raw, expect_change in test_cases:
        result = parse_compression_response(raw, a2)
        words  = len(result.split())
        status = "OK" if words <= _MAX_MEMORY_WORDS else "TOOLONG"
        print(f"  [{status:6s}] {words:3d} words | {result[:80]!r}{'…' if len(result) > 80 else ''}")

    print("\n[memory] Done.")
